### ISSUE TITLE
Mailing subscription help 

### ISSUE THREAD

**Issue by drawlia** [kelvinmo/soon#1]
Hi thank you so much for the wonderful jekyll theme. Just wanted to know, how to configure the mailing list subscription ?

**Comment by kelvinmo** [comment]
Firstly, as jekyll is a static web site generator, you will need to get an external mailing list service to host your mailing list.

The mailing list service should provide you with instructions on how to create a sign-up form, including a URL where the sign-up information should be sent.  You will need to place that URL into the `action` parameter under `subscribe` in `_config.yml`.  Depending on what fields the mailing list service URL expect, you may also need to modify `_includes/subscribe.html` to supply those fields.
